### ISSUE TITLE
`--ext-refs` is not working properly

### ISSUE THREAD

**Issue by mrstegeman** [pb33f/openapi-changes#191]
This new flag was added (per my request in #186) in [a894170](https://github.com/pb33f/openapi-changes/commit/a894170f4b3675fd731036fa9bbd5224401e2e5e). However, it doesn't seem to be working properly.

Here's a stripped down `openapi.yaml` to test with:
```
openapi: 3.0.3
paths:
  /metrics:
    post:
      tags:
        - metrics
      summary: Upload metrics.
      description: Proxies metrics to Prometheus and any other configured sinks.
      operationId: uploadMetrics
      parameters:
        - $ref: '#/components/parameters/XRequestIdHeaderParameter'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
components:
  schemas:
    Text:
      type: string
      description: Text string.
  responses:
    NoContent:
      description: No Content
      headers:
        x-request-id:
          $ref: '#/components/headers/x-request-id'
  parameters:
    XRequestIdHeaderParameter:
      description: |-
        Unique request ID. If one is not provided, it will be generated automatically and returned in the
        response headers. The request ID is useful when tracing logs.
      name: x-request-id
      in: header
      required: false
      schema:
        $ref: '#/components/schemas/Text'
  headers:
    x-request-id:
      description: Unique request ID, useful when tracing logs.
      required: false
      schema:
        $ref: '#/components/schemas/Text'
```

```
➜   openapi-changes summary -n --ext-refs -b ./openapi.yaml ./openapi.yaml
2025-02-19 21:51:24 ERROR unable to locate reference anywhere in the rolodex reference: #/components/headers/x-request-id
2025-02-19 21:51:24 ERROR unable to locate reference anywhere in the rolodex reference: #/components/headers/x-request-id
ERROR: cannot resolve reference `#/components/headers/x-request-id`, it's missing: $.components.headers['x-request-id'] [25:11]
ERROR: cannot resolve reference `#/components/headers/x-request-id`, it's missing: $.components.headers['x-request-id'] [25:11]
Error: cannot resolve reference `#/components/headers/x-request-id`, it's missing: $.components.headers['x-request-id'] [25:11]
cannot resolve reference `#/components/headers/x-request-id`, it's missing: $.components.headers['x-request-id'] [25:11]
```

**Comment by lupor** [comment]
I think this is related to the issue that i posted here: https://github.com/pb33f/openapi-changes/issues/190

**Comment by mrstegeman** [comment]
Ah yes, I think you're right!

**Comment by daveshanley** [comment]
fixed in `v0.0.76`

**Comment by mrstegeman** [comment]
@daveshanley This is still not working on 0.0.76. I'm getting the exact same error output.

**Comment by daveshanley** [comment]
Damn, sorry wil re-investigate.

**Comment by daveshanley** [comment]
This has been solved in `v0.2+`
